// Generated by CoffeeScript 1.9.3
(function() {
  var Socket, columns, createOPCStream, createStrand, height, i, socket, strand, stream, width;

  Socket = require("net").Socket;

  socket = new Socket();

  socket.setNoDelay();

  socket.connect(22000);

  createOPCStream = require("opc");

  stream = createOPCStream();

  stream.pipe(socket);

  width = 13;

  height = 63;

  createStrand = require("opc/strand");

  strand = createStrand(width * height);

  columns = [];

  i = 0;

  while (i < width) {
    columns.push(strand.slice(height * i, height * (i + 1)));
    i++;
  }

  module.exports = {
    height: height,
    width: width,
    stream: stream,
    strand: strand,
    columns: columns
  };

}).call(this);
